language: cpp

compiler:
  - gcc
  - clang

install:
  - time sudo apt-get update -qq
  - time sudo apt-get install -qq libmysqlcppconn-dev

script:
  - make

branches:
  only:
    - master
    - beta

os:
  - linux
  - osx
