language: cpp

sudo: false

cache: apt

notifications:
  email: false

_packages:
  - &default_packages
    - mysql-server
    - libmysqlcppconn-dev
    - make
    - zip
    - unzip
    - binutils # Needed for /usr/bin/ld
  - &GCC
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - *default_packages
          - g++-5-multilib
    before_install:
      - export CC="gcc-5"
      - export CXX="g++-5"
  - &Clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          - *default_packages
          - clang-3.6
    before_install:
      - export CC="clang-3.6"
      - export CXX="clang++-3.6"

matrix:
  fast_finish: true
  include:
    # GCC
    - compiler: gcc
      <<: *GCC
      env:
    - compiler: gcc
      <<: *GCC
      env: DEBUG=1
    - compiler: gcc
      <<: *GCC
      env: DEBUG=2
    # Clang
    - compiler: clang
      <<: *Clang
      env:
    - compiler: clang
      <<: *Clang
      env: DEBUG=1
    - compiler: clang
      <<: *Clang
      env: DEBUG=2

before_script:
  - export CC="$CC -Werror"
  - export CXX="$CXX -Werror"
  - mysql -e "CREATE USER sim@localhost IDENTIFIED BY 'sim'; CREATE DATABASE sim; GRANT ALL ON sim.* TO 'sim'@'localhost';" -u root

script:
  - make DEBUG=$DEBUG CXX="$CXX -v" build test
  - printf 'sim\nsim\nsim\nlocalhost\n' | make install run
  - wget -t 5 -T 1 --retry-connrefused http://127.7.7.7:8080/
  - cat index.html
  - cat build/logs/*.log
