language: cpp

compiler:
  - gcc
  - clang

cache: apt

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq proot mysql-server mysql-client libmysqlcppconn-dev

script:
  - make -kj
  - echo | sudo make install
  - (cd build && sudo -u sim ./sim-server)&
  - wget -t 5 -T 1 --retry-connrefused http://127.7.7.7:8080/
  - cat index.html

branches:
  only:
    - master
    - beta

notifications:
  email: false

matrix:
  fast_finish: true
