language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mysql-server mysql-client libmysqlcppconn-dev

script:
  - make -j
  - echo | sudo make install
  - (cd build && sudo -u sim ./sim-server)&
  - wget http://127.7.7.7:8080/
  - cat index.html

branches:
  only:
    - master
    - beta

notifications:
  email: false

matrix:
  fast_finish: true
