language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nginx mysql-server mysql-client php5-cli php5-fpm php5-mysql libmysqlcppconn-dev
  - sudo nginx

script:
  - make -j
  - echo | sudo make install
  - wget http://127.2.2.2/
  - cat index.html

branches:
  only:
    - master
    - beta

notifications:
  email: false

matrix:
  fast_finish: true
