language: cpp

sudo: false

cache: apt

notifications:
  email: false

_packages:
  - &default_packages
    - mysql-server
    - libmysqlcppconn-dev
    - make
    - zip
    - unzip
  - &GCC
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - *default_packages
          - g++-4.9-multilib
    before_install:
      - export CC="gcc-4.9"
      - export CXX="g++-4.9"
  - &Clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise
        packages:
          - *default_packages
          - libstdc++-4.9-dev # Proper version of std library
          - clang-3.4
    before_install:
      - export CC="clang"
      - export CXX="clang++"

matrix:
  fast_finish: true
  include:
    # GCC
    - compiler: gcc
      <<: *GCC
      env:
    - compiler: gcc
      <<: *GCC
      env: DEBUG=1
    - compiler: gcc
      <<: *GCC
      env: DEBUG=2
    # Clang
    - compiler: clang
      <<: *Clang
      env:
    - compiler: clang
      <<: *Clang
      env: DEBUG=1
    - compiler: clang
      <<: *Clang
      env: DEBUG=2

before_script:
  - $CC -v
  - $CXX -v
  - export CC="$CC -Werror"
  - export CXX="$CXX -Werror"
  - mysql -e "CREATE USER sim@localhost IDENTIFIED BY 'sim'; CREATE DATABASE sim; GRANT ALL ON sim.* TO 'sim'@'localhost';" -u root

script:
  - ls /usr/bin | grep clang
  - ls /usr/local/bin | grep clang
  # Compile this file with suppressed warning
  - if [ "$CXX" = "g++-4.9 -Werror" ]; then make src/lib/cpp_syntax_highlighter.o DEBUG=$DEBUG CXX='g++-4.9 -Wno-missing-field-initializers -Isrc/include'; fi
  # Proper compilation
  - make DEBUG=$DEBUG build test
  - printf 'sim\nsim\nsim\nlocalhost\n' | make install run
  - wget -t 5 -T 1 --retry-connrefused http://127.7.7.7:8080/
  - cat index.html
  - cat build/logs/*.log
