language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mysql-server mysql-client libmysqlcppconn-dev

script:
  - make -j
  - echo | sudo make install

branches:
  only:
    - master
    - beta

notifications:
  email: false

matrix:
  fast_finish: true
