language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_install:
  - time sudo apt-get update -qq
  - time sudo apt-get install -qq libmysqlcppconn-dev

install:
  - make

branches:
  only:
    - master
    - beta
