language: cpp

compiler:
  - gcc
  - clang

install:
  - time sudo apt-get update -qq
  - time sudo apt-get install -qq libmysqlcppconn-dev

script:
  - make -j

branches:
  only:
    - master
    - beta

notifications:
  email: false

matrix:
  fast_finish: true
