language: cpp

compiler:
  - gcc
  - clang

env:
  -
  - DEBUG=1
  - DEBUG=2

cache: apt

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - g++-4.9-multilib
    - clang-3.5
    - mysql-server
    - mysql-client
    - libmysqlcppconn-dev

install:
  # Compiler
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - if [ "$CC" = "clang" ]; then export CC="clang-3.5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5"; fi

before_script:
  - export CC="$CC -Werror"
  - export CXX="$CXX -Werror"
  - mysql -e "CREATE USER sim@localhost IDENTIFIED BY 'sim'; CREATE DATABASE sim; GRANT ALL ON sim.* TO 'sim'@'localhost';" -u root

script:
  - make -kj DEBUG=$DEBUG
  - printf 'sim\nsim\nsim\nlocalhost\n' | make install run
  - wget -t 5 -T 1 --retry-connrefused http://127.7.7.7:8080/
  - cat index.html
  - cat build/logs/*.log

notifications:
  email: false

matrix:
  fast_finish: true
